version: '2'
services:
    postgres:
      image: postgres:9.5
      restart: always
      ports:
       - "5432:5432"
      environment:
       - "POSTGRES_USER=admin"
       - "POSTGRES_PASSWORD=123456"
       - "POSTGRES_DB=gogs"
      networks:
       - gogs
    gogs:
      image: gogs/gogs:0.11
      restart: always
      ports:
       - "10022:22"
       - "3000:3000"
      links:
       - postgres
      environment:
       - "RUN_CROND=true"
      networks:
       - gogs
      depends_on:
       - postgres

networks:
    gogs:
      driver: bridge